--- !ditz.rubyforge.org,2008-03-06/project 
name: cpan-packager
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: cpan-packager
- !ditz.rubyforge.org,2008-03-06/component 
  name: bugs
- !ditz.rubyforge.org,2008-03-06/component 
  name: main
- !ditz.rubyforge.org,2008-03-06/component 
  name: debian
- !ditz.rubyforge.org,2008-03-06/component 
  name: redhat
releases: []

