---
global:
  fix_module_name:
    - from: Template::Toolkit
      to:   Template
  fix_package_depends: []
  no_depends:
    - module: mod_perl
  skip_name_resolve_modules: []
modules:
  - module: CGI::Simple
    no_depends:
     - module: IO::Scalar
  - module: Test::Exception
    depends:
      - module: Test::Simple
    no_depends:
      - module: Test::Builder::Tester
  - module: FindBin::libs
    skip_test: 1
  - module: HTTP::Request::AsCGI
    skip_build: 1
  - module: IO::Compress::Base
    skip_build: 1
  - module: MooseX::MethodAttributes::Inheritable
    skip_build: 1
  - module: Perl::MinimumVersion
    skip_test: 1
  - module: PathTools
    skip_build: 1
  - module: Scalar::List::Utils
    skip_build: 1
