---
global:
  cpan_mirrors:
    - file:///home/dann/.cpanpackager/minicpan/
  fix_module_name:
    - from: Template::Toolkit
      to:   Template
  fix_package_depends: []
  no_depends:
    - module: mod_perl
    - module: CGI
    - module: Class::Accessor
    - module: Compress::Zlib
    - module: Devel::PPPort
    - module: Encode
    - module: ExtUtils::MakeMaker
    - module: File::Copy
    - module: File::Spec
    - module: File::Spec::Functions
    - module: File::Spec::Mac
    - module: File::Spec::OS2
    - module: File::Spec::Unix
    - module: File::Spec::Win32
    - module: File::Temp
    - module: 'Filter # brokes?'
    - module: HTTP::Request
    - module: HTTP::Response
    - module: IO::stringy
    - module: IO::Compress::Base
    - module: kurila
    - module: LWP::UserAgent
    - module: List::Util
    - module: Module::Install
    - module: Module::Install::AuthorTests
    - module: PathTools
    - module: perl
    - module: Pod::Parser
    - module: Scalar::List::Utils
    - module: Scalar::Util
    - module: Test::Harness
    - module: version
    - module: Sub::Uplevel
    - module: Text::Exception
  skip_name_resolve_modules: []

modules:
  - module: CGI::Simple
    no_depends:
     - module: IO::Scalar
  - module: Test::Exception
    depends:
      - module: Test::Simple
    no_depends:
      - module: Test::Builder::Tester
  - module: FindBin::libs
    skip_test: 1
  - module: HTTP::Request::AsCGI
    skip_build: 1
  - module: IO::Compress::Base
    skip_build: 1
  - module: MooseX::MethodAttributes::Inheritable
    skip_build: 1
  - module: Perl::MinimumVersion
    skip_test: 1
  - module: PathTools
    skip_build: 1
  - module: Scalar::List::Utils
    skip_build: 1
  - module: Module::Setup 
    no_depends:
      - module: Module::Install::AuthorTests
  - module: Catalyst::Runtime
    no_depends:
      - module: HTTP::Request::AsCGI
      - module: Test::Exception 
