---
global:
  fix_meta_yml_modules:
    - Any::Moose
    - HTTP::Request::AsCGI
    - MooseX::MethodAttributes
  fix_module_name:
    IO::Compress: IO::Compress::Base
    libwww-perl: LWP::UserAgent
    podlators: Pod::Man
    Scalar::Util: Scalar::List::Utils
  fix_package_depends: ~
  no_depends:
    - CGI
    - Class::Accessor
    - Compress::Zlib
    - Devel::PPPort
    - Encode
    - ExtUtils::MakeMaker
    - File::Copy
    - File::Spec
    - File::Spec::Functions
    - File::Spec::Mac
    - File::Spec::OS2
    - File::Spec::Unix
    - File::Spec::Win32
    - File::Temp
    - 'Filter # brokes?'
    - HTTP::Request
    - HTTP::Response
    - IO::stringy
    - IO::Compress::Base
    - kurila
    - LWP::UserAgent
    - List::Util
    - Module::Install
    - Module::Install::AuthorTests
    - PathTools
    - perl
    - Pod::Parser
    - Pod::Parser
    - Scalar::List::Utils
    - Scalar::Util
    - Test::Harness
    - version

  skip_name_resolve_modules:
    - Class::DBI
    - Class::DBI::AbstractSearch
    - Date::Parse
    - HTTP::Request
    - HTTP::Response
    - IO::Scalar
    - IO::stringy
    - LWP::UserAgent
    - PathTools
    - perl
    - PerlInterp
    - Template

modules:
  - module: Archive::Tar
    no_depends:
      - Compress::Zlib
      - IO::Compress::Bzip2
      - IO::Compress::Gzip
  # META.yml is broken...
  - module: Any::Moose
    build_skip: 1
  - module: CGI::Simple
    no_depends:
      - IO::Scalar
  - module: CGI::Ajax
    no_depends:
      - CGI::Ajax
  - module: CPAN::Packager
    depends:
      - CPANPLUS::Backend
      - FindBin::libs
      - IPC::System::Simple
      - LWP::UserAgent
      - Module::Depends
      - Module::CoreList
      - Mouse
      - Path::Class
      - RPM::Specfile
      - UNIVERSAL::require
      - File::Copy
      - Hash::Merge
      - List::MoreUtils
      - YAML
      - MouseX::Getopt
      - List::MoreUtils
      - List::Compare
  - module: Class::Accessor
    depends:
      - Class::Classgen::Attribute
    no_depends:
      - Class::Classgen::classgen
  - module: Class::Classgen::classgen
    build_skip: 1
  - module: Class::DBI::AbstractSearch
    depends:
      - Class::DBI # hmm.
    no_depends:
      - Class::DBI::AbstractSearch
  - module: Class::Trigger
    no_depends:
      - IO::stringy
      - IO::Scalar
  - module: Catalyst::Runtime
    no_depends:
      - HTTP::Request::AsCGI
      - MooseX::MethodAttributes::Inheritable
  - module: DBIx::Class
    skip_test: 1
  - module: File::Spec
    build_skip: 1
  - module: File::Find::Rule::Perl
    skip_test: 1
  - module: FindBin::libs
    skip_test: 1
  - module: Getopt::Long::Descriptive
    no_depends:
      - IO::stringy
      - IO::Scalar
  - module: HTTP::Engine
    no_depends:
      - URI
      - IO::stringy
      - IO::Scalar
      - Any::Moose
  - module: HTTP::Server::Simple
    depends:
      - URI
    no_depends:
      - ASNMTAP
  # META.yml is broken...
  - module: HTTP::Request::AsCGI
    build_skip: 1
  - module: IPC::System::Simple
    no_depends:
      - Solaris::PerlGcc
  - module: IO::Compress::Base
    build_skip: 1
  - module: JSON::Any:
    depends:
      - JSON
      - JSON::XS
  - module: Log::Dispatch::Config
    no_depends:
      - IO::stringy
      - IO::Scalar
  - module: Module::Setup:
    no_depends:
      - Module::Install::AuthorTests
  - module: Mouse:
    skip_test: 1
  # META.yml is broken...
  - module: MooseX::MethodAttributes
    build_skip: 1
  - module: MooseX::MethodAttributes::Inheritable
    build_skip: 1
  - module: Perl::MinimumVersion
    skip_test: 1
  - module: PathTools:
    build_skip: 1
  - module: Scalar::List::Utils
    build_skip: 1
  - module: Test::Exception
    depends:
      - Test::Simple
    no_depends:
      - Test::Builder::Tester
  - module: YAML:
    no_depends:
      - Filter

