---
global:
  fix_meta_yml_modules:
    - Any::Moose
    - HTTP::Request::AsCGI
    - MooseX::MethodAttributes
  fix_module_name:
    - from: IO::Compress
      to: IO::Compress::Base
    - from: libwww-perl
      to: LWP::UserAgent
    - from: podlators
      to: Pod::Man
    - from: Scalar::Util
      to: Scalar::List::Utils
  fix_package_depends: ~
  no_depends:
    - module: CGI
    - module: Class::Accessor
    - module: Compress::Zlib
    - module: Devel::PPPort
    - module: Encode
    - module: ExtUtils::MakeMaker
    - module: File::Copy
    - module: File::Spec
    - module: File::Spec::Functions
    - module: File::Spec::Mac
    - module: File::Spec::OS2
    - module: File::Spec::Unix
    - module: File::Spec::Win32
    - module: File::Temp
    - module: 'Filter # brokes?'
    - module: HTTP::Request
    - module: HTTP::Response
    - module: IO::stringy
    - module: IO::Compress::Base
    - module: kurila
    - module: LWP::UserAgent
    - module: List::Util
    - module: Module::Install
    - module: Module::Install::AuthorTests
    - module: PathTools
    - module: perl
    - module: Pod::Parser
    - module: Scalar::List::Utils
    - module: Scalar::Util
    - module: Test::Harness
    - module: version

  skip_name_resolve_modules:
    - Class::DBI
    - Class::DBI::AbstractSearch
    - Date::Parse
    - HTTP::Request
    - HTTP::Response
    - IO::Scalar
    - IO::stringy
    - LWP::UserAgent
    - PathTools
    - perl
    - PerlInterp
    - Template

modules:
  - module: Archive::Tar
    no_depends:
      - module: Compress::Zlib
      - module: IO::Compress::Bzip2
      - module: IO::Compress::Gzip
  # META.yml is broken...
  - module: Any::Moose
    skip_build: 1
  - module: CGI::Simple
    no_depends:
      - module: IO::Scalar
  - module: CGI::Ajax
    no_depends:
      - module: CGI::Ajax
  - module: CPAN::Packager
    depends:
      - module: CPANPLUS::Backend
      - module: FindBin::libs
      - module: IPC::System::Simple
      - module: LWP::UserAgent
      - module: Module::Depends
      - module: Module::CoreList
      - module: Mouse
      - module: Path::Class
      - module: RPM::Specfile
      - module: UNIVERSAL::require
      - module: File::Copy
      - module: Hash::Merge
      - module: YAML
      - module: MouseX::Getopt
      - module: List::MoreUtils
      - module: List::Compare
  - module: module: Class::Accessor
    depends:
      - module: Class::Classgen::Attribute
    no_depends:
      - module: Class::Classgen::classgen
  - module: Class::Classgen::classgen
    skip_build: 1
  - module: Class::DBI::AbstractSearch
    depends:
      - module: Class::DBI # hmm.
    no_depends:
      - module: Class::DBI::AbstractSearch
  - module: Class::Trigger
    no_depends:
      - module: IO::stringy
      - module: IO::Scalar
  - module: Catalyst::Runtime
    no_depends:
      - module: HTTP::Request::AsCGI
      - module: MooseX::MethodAttributes::Inheritable
  - module: DBIx::Class
    skip_test: 1
  - module: File::Spec
    skip_build: 1
  - module: File::Find::Rule::Perl
    skip_test: 1
  - module: FindBin::libs
    skip_test: 1
  - module: Getopt::Long::Descriptive
    no_depends:
      - module: IO::stringy
      - module: IO::Scalar
  - module: HTTP::Engine
    no_depends:
      - module: URI
      - module: IO::stringy
      - module: IO::Scalar
      - module: Any::Moose
  - module:  module: HTTP::Server::Simple
    depends:
      - module: URI
    no_depends:
      - module: ASNMTAP
  # META.yml is broken...
  - module: HTTP::Request::AsCGI
    skip_build: 1
  - module: IPC::System::Simple
    no_depends:
      - module: Solaris::PerlGcc
  - module: IO::Compress::Base
    skip_build: 1
  - module: JSON::Any:
    depends:
      - module: JSON
      - module: JSON::XS
  - module: Log::Dispatch::Config
    no_depends:
      - module: IO::stringy
      - module: IO::Scalar
  - module: Module::Setup:
    no_depends:
      - module: Module::Install::AuthorTests
  - module: Mouse:
    skip_test: 1
  # META.yml is broken...
  - module: MooseX::MethodAttributes
    skip_build: 1
  - module: MooseX::MethodAttributes::Inheritable
    skip_build: 1
  - module: Perl::MinimumVersion
    skip_test: 1
  - module: PathTools:
    skip_build: 1
  - module: Scalar::List::Utils
    skip_build: 1
  - module: Test::Exception
    depends:
      - module: Test::Simple
    no_depends:
      - module: Test::Builder::Tester
  - module: YAML:
    no_depends:
      - module: Filter

