---
global:
  fix_meta_yml_modules:
    - HTTP::Request::AsCGI
  fix_module_name:
    - from: Template::Toolkit
      to:   Template
  fix_package_depends: []
  no_depends:
    - module: mod_perl
  skip_name_resolve_modules: []
modules:
  - module: CGI::Simple
    no_depends:
     - module: IO::Scalar
  - module: Test::Exception
    depends:
      - module: Test::Simple
    no_depends:
      - module: Test::Builder::Tester
  - module: FindBin::libs
    skip_test: 1
  - module: CGI::Simple

